//This contains the English words with Samoan equivalents

var EnglishToSamoanWords = [
["a","le","art."],
["a little sick","fa'ama'ima'i","v."],
["abandon","tu'ulafoa'i","v."],
["abandoned","tu'ufua","adj."],
["able","mafai","v."],
["about","e uiga i","prep."],
["about","uiga","prep."],
["about","pe","adv."],
["above","luga","adj."],
["absorb","mimiti","v."],
["abundance","matalasi","adj."],
["abundance","mau","n."],
["abuse","fa'asauaina","n."],
["accept","talia","v."],
["accepted","taulia","v."],
["accidently","mao","adv."],
["accompany","momoli","v."],
["accomplishment","fa'ataunuga","n."],
["account","tusitupe","n."],
["accurate","ala","adj."],
["accustomed","masani","v."],
["ache","gaoi","v."],
["acre","'eka","n."],
["act like a child","fa'atama","v."],
["active","tiotio","adj."],
["activities","gaoioiga","n."],
["actor","faitifaga","n."],
["actress","faitifaga","n."],
["adapt","fa'amasani","v."],
["add","fa'aopoopo","v."],
["add salt","fa'amasima","v."],
["address (mailing)","tuatusi","n."],
["administer","fa'afoe","v."],
["administration","pulega","n."],
["admire","momo'o","v."],
["adults","tagata matutua","n."],
["advantage","itulelei","n."],
["advertise","fa'asalalau","v."],
["advice","fautuaga","n."],
["advise","fautua","v."],
["advise or exhort","apoapoa'i","v."],
["afflict","pagatia","v."],
["afford","ausia","v."],
["afford","gafatia","v."],
["after","'ina 'ua 'uma","conj."],
["after","pe'a 'uma","conj."],
["afternoon","afiafi","n."],
["aftwerwards","mulimuli ane","adv."],
["again","fo'i","adv."],
["again","toe","adv."],
["age","matua","n."],
["agitated","vevesi","adj."],
["agree","fetaui","v."],
["agree","malie","v."],
["agreeable","lotomalie","adj."],
["agreement","lotogatasi","n."],
["agreement","maliega","n."],
["agreement","tafatasi","n."],
["agreement","feagaiga","n."],
["air","'ea","n."],
["albino","tetea","n."],
["alert","mata'ala","v."],
["algae","limu","n."],
["all (day)","'atoa","adj."],
["all contries","atulaulau","n."],
["allow","tatala","v."],
["allowed","taga","n."],
["allowed","fa'ataga","v."],
["almost","to'etiti","adj."],
["along","ane","dir."],
["also","fo'i","adv."],
["although","e ui ina","conj."],
["always","masani lava","v."],
["ambitious","fia sili","adj."],
["ambush","fa'apo","v."],
["amen","amene","v."],
["ancestors","tupuaga","n."],
["anchor","taula","n."],
["anchorage","taulaga","n."],
["and","ma","conj."],
["and  ","'ae","conj."],
["and then (verb)","'ona.(verb).ai lea","conj."],
["angel","agelu","n."],
["anger or wrath","to'asa","n."],
["angry","ita","v."],
["angry","ma'ema'ea","v."],
["angry","to'atama'i","adj."],
["angry (about food)","'aimeo","adj."],
["animal","manu","n."],
["animal","meaola","n."],
["animals (wild)","'aivao","adj."],
["ankle","tapuvae","n."],
["anklet","tauvae","n."],
["anniversary","fa'amanatuina","n."],
["announce","folafola","v."],
["announce","tolaulau","v."],
["annual","fa'aletausaga","v."],
["answer","tali","v."],
["any","so'o","adj."],
["any, a","se","art."],
["any, are","ni","art."],
["apologize","fa'amalulu","v."],
["apologize","fa'ato'ese","v."],
["apology","fa'ato'esega","n."],
["appear","fa'a'ali","v."],
["appear","fotu","v."],
["appear (partially)","aliali","v."],
["apple","apu","n."],
["apply","'apalai","v."],
["apply ointment","nini","v."],
["appoint","tofi","v."],
["appreciate","talisapai","v."],
["appropriate","ono mea","adj."],
["approve","malie","v."],
["approved (lady)","tausa'afia","v."],
["April","'Aperila","n."],
["Are there","'E iai","q."],
["area","vaega","n."],
["argue","finau","v."],
["argue ","fefinaua'i","v."],
["arguement","fefinaua'i","n."],
["arguement","finauga","n."],
["arm","lima","n."],
["armpit","'ao'ao","n."],
["arms folded","pi'ilima","v."],
["arrange","fa'atulaga","v."],
["arrangement","fa'atulagaga","n."],
["arrive","o'o","v."],
["arrive","taunu'u","v."],
["arrive at night","palepo","v."],
["arrive first","mua","v."],
["arrive late","siliga","v."],
["arrogant","fa'amaualuga","adj."],
["arrogant","fa'asausili","adj."],
["arrogant","fia poto","adj."],
["arrow","au","n."],
["as","pei","conj."],
["as though","peisea'i","conj."],
["as usual","mea masani","adj."],
["ash","lefulefu","n."],
["ashamed","ma","adj."],
["ashore","uta","n."],
["ask","fesili","v."],
["assemble","fa'apotopoto","v."],
["asset","aseta","n."],
["assign","tofi","v."],
["association","asosi","n."],
["at","i","prep."],
["atone","togisala","v."],
["attack","osofa'i","v."],
["attempt","taumafai","v."],
["attend","auau","v."],
["August","'Aukuso","n."],
["aunt","uso o lo'u tina","n."],
["Australia","'Ausetalia","n."],
["available","avanoa","adj."],
["avocado","'avoka","n."],
["avoidable","ma'alofia","adj."],
["away","atu","dir."],
["awe inspiring","mata'utia","adj."],
["axe","to'i","n."],
["back","papatua","n."],
["back","patua","n."],
["bad","leaga","adj."],
["bad","seu","adj."],
["bad behavior","agaleaga","adj."],
["badly reported","ta'uleagaina","v."],
["baffle","fa'apalo","v."],
["bag","taga","n."],
["bag, basket","'ato","n."],
["bait","maunu","n."],
["bake in an oven","tao","v."],
["bakery","falefalaoa","n."],
["baking powder","fefete","n."],
["bald","tula","adj."],
["ball","polo ","n."],
["ballot","palota","n."],
["banana","fa'i","n."],
["banana plantation","togafa'i","n."],
["banana porridge","suafa'i","n."],
["band","fa'aili","n."],
["band aid","mea fa'apipi'i","n."],
["bandage","fusi","v."],
["banish","fa'ate'a","v."],
["bank","faletupe","n."],
["baptise","papatiso","v."],
["baptism","papatisoga","n."],
["baptism","papitema","n. "],
["barbeque","papakiu","n."],
["barrel","paelo","n."],
["based","tau","n."],
["basketball","pasiketipolo","n."],
["bat","pate","n."],
["bath","ta'elega","n."],
["bathe","ta'ele","v."],
["bathing soap","molita'ele","n."],
["battery","ma'a moli uila","n."],
["battle","taua","n."],
["be","iai ","v."],
["be a tenant","mautotogi","v."],
["be as far as","pau","v."],
["be in favor","lotomalie","adj."],
["be last","muli","v."],
["be the best","aupito sili","v."],
["be the leader","ta'imua","v."],
["be together","fa'atasi","adv."],
["be condemned","nofosala","adj."],
["beach","matafaga","n."],
["beach (a boat)","tuta","v."],
["beach fale","fale tulisi","n."],
["bear as a burden","tau'ave","v."],
["bear false witnes","molimau pepelo","v."],
["bear in mind","fa'atalatala","v."],
["beard","'ava","n."],
["bearing fruit","fua","adj."],
["beat","safue","v."],
["beat","sasa","v."],
["beat (person)","fasi","v."],
["beat of the heart","tata","n,"],
["beautiful","matagofie","adj."],
["because","'aua","conj."],
["because","'ona","conj."],
["because","leaga","conj."],
["because of","'ona o","conj."],
["become","'avea ma","v."],
["bed","moega","n."],
["bedroom","potu moe","n."],
["beer","pia","n."],
["before","'ae le'i","conj."],
["before","a'o le'i","conj."],
["beg","'ai'oi","v."],
["beg","'aisi","v."],
["beg for","ole","v."],
["behave","amio","v."],
["behavior","amioga","n."],
["behavior, conduct","aga","n."],
["behind","tua",""],
["behind","tua","loc."],
["belief","mau","n."],
["belief","talitonuga","n."],
["believe","talitonu","v."],
["believe","fa'atuatua","v."],
["bell","logo","n."],
["bell signal","fa'ailo","n."],
["belly","'ona","n."],
["belonging to","a","prep."],
["beloved","mamae","adj."],
["below","lalo","adv."],
["belt","fusipa'u","n."],
["belt buckle","kalauna","n."],
["bend","tulolo","v."],
["bend down","fa'ano'uno'u","v."],
["bend or curve","fa'api'o","n."],
["best","sili","adj."],
["bet","peti","v."],
["betray","fa'alata","v."],
["better","sili","adj."],
["between","le va","dir."],
["beyond","autafa","n."],
["beyond","tala atu","adj."],
["biased","fa'aitu'au","adj."],
["bicycle","uila","n."],
["bid goodbye","fa'atofa","v."],
["big","lapo'a","adj."],
["big or large","tele","adj."],
["big toe","vaematua","n."],
["bill","pili","n."],
["billiards","piliaki","n."],
["bind","fusi","v."],
["bind","noanoa","v."],
["bird","manulele","n."],
["birth certificate","pepa fanau","n."],
["birthday","aso fanau","n."],
["bishop","epikopo","n."],
["bite","a'ati","v."],
["bite or sting","u","v."],
["bite or sting","u","n."],
["bitter","'o'ona","adj."],
["black","uliuli","adj."],
["blade (of knife)","lau","n."],
["blame","tu'ua'i","v."],
["blame","tu'ua'i fua","v."],
["blamed","tu'ua'ia","v."],
["bless","fa'amanuia","v."],
["blessed","'amu'ia","adj."],
["blessing","fa'amanuiaga","n."],
["blind","ivi","adj."],
["blind","tauaso","v."],
["blinds (palm)","pola","n."],
["blink","'emo'emo","v."],
["block","poloka","v."],
["blood","toto","n."],
["blood sugar","suka o le toto","n."],
["blow","feula","v."],
["blow (instrument)","ili","v."],
["blow (from wind)","agi","v."],
["blow (nose)","fogi","v."],
["blow gently","agiagi","v."],
["blue","lanu moana","adj."],
["blunt","matatupa","adj."],
["blunt","tulali","adj."],
["blurry","nenefu","adj."],
["board","laupapa","n."],
["boast","mimita","v."],
["boast","mitamitavale","v."],
["boastful","gugutu","adj."],
["boat","va'a","n."],
["boat crew","'auva'a","n."],
["body","tino","n."],
["body hair","fulufulu","n."],
["boil","fa'apuna","v."],
["boil (food)","saka","v."],
["boil water","puna","v."],
["bone","ivi","n."],
["bone","ponaivi","n. "],
["bonito (fish)","atu","n."],
["book","tusi","n."],
["book keeper","tausitusi","n."],
["bookshelf","fatatusi","n."],
["boring","iva","adj."],
["boring (person)","iva","adj."],
["born","fanau","v."],
["borrow","nono","v."],
["boss","pule","n."],
["bottle","fagu","n."],
["bottom","muli","n."],
["boundry","tua'oi","n."],
["bow down","ifo","v."],
["bow head (down)","punou","v."],
["bowl in cricket ","tete'a","v."],
["bowl for kava","tanoa","n."],
["box","pusa","n."],
["boxing","taua'ifusu","n."],
["boxing match","fusu'aga","n."],
["boy","tama","n."],
["boy","sole","n."],
["bracelet","taulima","n."],
["braid of hair","fili","n."],
["brain","mafaufau","n."],
["brave","lototele","adj."],
["brave","toa","adj."],
["bread","falaoa","n."],
["breadfruit","'ulu","n."],
["break","ta'e","v."],
["break","gagau","v."],
["break","gau","v."],
["break (stick)","motu","v."],
["break a rock","foa","v."],
["break in pieces","nuti","v."],
["break out (illness)","oso","v."],
["break up","talepe","v."],
["breakfast","ti","n."],
["breast","susu","n."],
["breastfeed","fa'asusu","v."],
["breathe","manava ","v."],
["breeze","savili","n."],
["brewery","falepia","n."],
["brick","piliki","n."],
["bridge","auala laupapa","n."],
["bring","'aumai","v."],
["bring to pass","fa'ataunu'u","v."],
["bring to vote","tafale","v."],
["Britian","Peretania","n."],
["brittle","ma'ale'ale","adj."],
["broil","tunupa'u","v."],
["broken (bone)","gau","v."],
["broom","salu","n."],
["brother of woman","tuagane","n."],
["brother of man","uso","n."],
["brown","'ena'ena","adj."],
["brush away","tafi","v."],
["bucket","pakete","n."],
["budget","pakeke","n."],
["build","fau","v."],
["build","gaosi","v."],
["bull","pulu","n."],
["bulldozer","katapila","n."],
["bullet","ututau","n."],
["bullet","pulu","n."],
["bun","pani","n."],
["bunch of bananas","'aufa'i","n."],
["bundle","fusi","n."],
["bundle of leaves","'aulama","n."],
["buoy","pole","n."],
["burden","avega","n."],
["burdened","mafatia","adj."],
["burn ","mu","v."],
["burn (eg. trash)","susunu","v."],
["burst","pa","v."],
["bury","tanu","v."],
["bus","pasi","n."],
["bus driver","'avepasi","n."],
["bush or forest","vao","n."],
["business","pisinisi","n."],
["busy","pisi","adj."],
["but","'ae","conj."],
["but","peita'i","conj."],
["butcher's shop","fale fasipovi","n."],
["butter","fa'apata","v."],
["butter","pata","n."],
["button","fa'amau","v."],
["buy","fa'atau","v."],
["bye","fa",""],
["cabbage","kapisi","n."],
["cabbage garden","togakapisi","n."],
["cabinet","kapeneta","n."],
["cake","keke","n."],
["calamity","mala","n."],
["calender","kalena","n."],
["call","alaga","v."],
["call","fono","v."],
["call (telephone)","vili","v."],
["call (to someone)","vala'au","v."],
["call over (lipsink)","miti","v."],
["calm","filemu","adj."],
["camel","kamela","n."],
["camera","meapueata","n."],
["can","'apa","n."],
["Can","'E mafai","q."],
["can","mafai","v."],
["can of soda","'apainu","n."],
["canal","kanala","n."],
["cancer","kanesa","n."],
["candle","moli","n."],
["candy","lole","n."],
["cane or staff","to'oto'o","n."],
["canned fish","'eleni","n."],
["canoe,double hull","'alia","n."],
["canyon","vanu","n."],
["captian","kapeteni","n."],
["car","ta'avale","n."],
["carbon","kaponi","n."],
["care","tausiga","n."],
["care for","tausi","v."],
["careful","fa'aeteete","v."],
["carefully","fa'aeteetega","adv."],
["careless","fa'atalale","adj."],
["careless","fa'atamala","adj."],
["carpet","kapeta","n."],
["carrot","kaloti","n."],
["carry","amo","v."],
["carry","ave","v."],
["carry","sa'esa'e","v."],
["carry ","sapai","v."],
["carry (on back)","fafa","v."],
["carry a burden","fa'afafa","v."],
["carry under arms","afisi","v."],
["carton","pepa","n."],
["carton of milk","pepa susu","n."],
["cashier","talitupe","n."],
["cassette","kaseti","n."],
["casually","fa'asamasamanoa","adj."],
["cat","pusi","n."],
["catch","pu'e","v."],
["catch (object)","sapo","v."],
["catch with a rope","sele","v."],
["cattle","povi","n."],
["cattle farm","pa povi","n."],
["cause","mafua","v."],
["cause","mafuaga","n."],
["cause to get wet","fa'asusu","v."],
["cause to fall","fa'apau","v."],
["cause confusion","fa'afememea'i","v."],
["cause to scatter","fa'ata'ape'ape","v."],
["cause to slide ","fa'asolo","v."],
["cause to stand up","fa'atu","v."],
["cause to swell","fa'afefete","v."],
["cave","ana","n."],
["ceiling","fa'aalo","n."],
["celebration","fiafia","n."],
["cemetary","fanuatanu","n."],
["cent","sene","n."],
["center","ogatotonu","n."],
["centipede","atualoa","n."],
["ceremonial gift","ta'alolo","n."],
["ceremony for new","umusaga","n."],
["certain","mautinoa","adj."],
["certificate","tusipasi","n."],
["chair","nofoa","n."],
["chairman","ta'ita'ifono","n."],
["chalk","penisina","n."],
["chalk","sioka","n."],
["challenge","lu'i","v."],
["champion","siamupini","n."],
["change","sui","v."],
["change","sui","n."],
["charcoal","malala","n."],
["chase","tuli","v."],
["chase away","tuliese","v."],
["cheap","taugfoie","adj."],
["cheating husband","fa'aoleole","n."],
["check","siaki","n."],
["cheeky","ulavale","adj."],
["cheeky","tautalaitiiti","adj."],
["cheers! ","manuia","v."],
["cheese","sisi","n."],
["chest","fatafata","n."],
["chest","pusa","n."],
["chest","sefe","n."],
["chestnut tree","ifi","n."],
["chew","lamu","v."],
["chicken","moa","n."],
["chicken soup","suamoa","n."],
["chief","ali'i","n."],
["chief","matai","n."],
["chiefs or leaders","faipule","n."],
["child","tamaitiiti","n."],
["child, adopted","tamafai","n."],
["children","fanau","n."],
["children","tamaiti","n."],
["chile pepper","polo fe'u","n."],
["chin","'auvae","n."],
["China","Saina","n."],
["chocolate","sukalati","n."],
["choice","filifiliga","n."],
["choir","'aufaipese","n."],
["choose","filifili","v."],
["chop","tipitipi","v."],
["chopsuey","sapasui","n."],
["chow mein","siaumeni","n."],
["Christ","keriso","n."],
["christian","kerisiano","n."],
["Christmas","Kilisimasi","n."],
["church","'ekalesia","n."],
["church","falesa","n."],
["church group","'aulotu","n."],
["church service","lotu","n."],
["cigar","sika","n."],
["cigarette","sikaleti","n."],
["cinnamon","kinamoni","n."],
["circle","li'o","n."],
["circumcised","peritomeina","adj."],
["clap hands","pati","v."],
["clap hands","patipati","v."],
["clasp","opo","v."],
["class","vasega","n."],
["clean","fa'amama","v."],
["clean","mama","adj."],
["cleanliness","tumama","n."],
["clear","fa'amama","v."],
["clear","mama","adj."],
["clear","manino","adj."],
["clear land","lafoga","n."],
["clerk","failautusi","n."],
["clever","poto","adj."],
["clever","atamai","adj."],
["cliff","mateo","n."],
["climate","tau","n."],
["climax","taualuga","n."],
["climb","a'e","v."],
["close","lata","adj."],
["close","latalata","adj."],
["close","tapuni","v."],
["close (eyes only)","moe'i'ini","v."],
["close curtains","pupuni","v."],
["closing","fa'aiu","n."],
["cloth","'ie","n."],
["clothes","ofu","n."],
["clothes","lavalava","n."],
["clothing","laei","n."],
["cloud","ao","n."],
["cloudy","auaoa","adj."],
["cloudy","paolo","adj."],
["club","kalapu","n."],
["clumsy","fa'avasivasi","adj."],
["clumsy","vasi","adj."],
["cluster (fruits)","taufui","n."],
["coal","koale","n."],
["coastal waters","gataifale","n."],
["coat","peleue","n."],
["cockroach","mogamoga","n."],
["cocoa","koko","n."],
["cocoa plantation","togakoko","n."],
["cocoa with rice","koko alaisa","n."],
["coconut (mature)","popo","n."],
["coconut biscuits","masipopo","n."],
["coconut cream","pe'epe'e","n."],
["coconut husk","pulu","n."],
["coconut leaf","launiu","n."],
["coconut plantation","toganiu","n."],
["coconut porridge","vaisalo","n."],
["coconut tree","niu","n."],
["coffee","kofe","n."],
["coincide","fetaui","v."],
["cold","malulu","adj."],
["cold (body, food)","ma'alili","adj."],
["cold (sick)","fulu","n."],
["collapse","masofa","v."],
["collar","kola","n."],
["collect","ao","v."],
["collect","aoao","v."],
["collect","aofia","v."],
["collect","tae","v."],
["collection(money)","saogatupe","n."],
["collection(things)","saofaga","n."],
["college","kolisi","n."],
["collide against","fetoa'i","v."],
["colon (:)","kolona","n."],
["colony","kolone","n."],
["color","lanu","n."],
["colorful","felanulanua'i","adj."],
["comb","selu","n.v."],
["combination","tu'ufa'atasiga","n."],
["come","sau","v."],
["come (polite)","afio mai","v."],
["come back","toe sau","v."],
["come from orig.","pogai","v."],
["come repeatedly","utu sau","v."],
["comedy","faleaitu","n."],
["comfort","fa'amalie","v."],
["comfort","fa'amafanafana","v."],
["comma","koma","n."],
["command","fa'atonu","v."],
["command","poloa'i","v."],
["command","poloa'iga","n."],
["commissionar","komesina","n."],
["commit adultry","mulilua","v."],
["commit sucicide","pule i le ola","v."],
["committee","komiti","n."],
["committee house","falekomite","n."],
["common (beliefs)","ta'atele","adj."],
["communicate","feso'ota'i","v."],
["communicate","talanoa fesootai","v."],
["communication","feso'ota'iga","n."],
["communist","kominisi","n."],
["company","kamupani","n."],
["compare","fa'atusatusa","v."],
["comparison","fa'atusatusaga","n."],
["compete","tausinio","v."],
["compete","tauva","v."],
["competition","tausinioga","n."],
["competition","tauvaga","n."],
["complain","fa'atio","v."],
["complain","tio","v."],
["complain","faitio","v."],
["complaint","faitioga","n."],
["complete","'atoa","adj."],
["complete","fa'a'ato'atoa","v."],
["complicate","fa'afaigata","v."],
["complicated","felefele","adj."],
["compliment","fa'avi'ivi'i","n."],
["compliment","taufa'ase'e","n."],
["compose (song)","fatu","v."],
["compost","fa'apala","n."],
["computer","komipiuta","n."],
["conceded","fiapoto","v."],
["conceited","fa'amaualuga","adj."],
["concern","uiga","v."],
["concert","koneseti","n."],
["conch shell","foafoa","n."],
["conclude","fa'a'iu","v."],
["conclude","fa'a'uma","v."],
["conclusion","fa'atofala'iga","n."],
["conditions","tu'utu'uga","n."],
["conference","koniferenisi","n."],
["confess","salamo","v."],
["confine or limit","fa'apito","v."],
["confused","fememea'i","adj."],
["confusion","fenumia'iga","n."],
["confusion","numi","n."],
["congratulate","fa'amalo","v."],
["congratulations","malo","interj."],
["connect","ogatasi","v."],
["connect","feso'ota'i","v."],
["connection of 2+","so'otaga","n."],
["conscience","lotofuatiaifo","n."],
["conservation area","fa'asao","n."],
["conserve","fa'asao","v."],
["considered","amana'ia","v."],
["consolidate","fa'amautu","v."],
["consonant","konesane","n."],
["conspire","pulepule","v."],
["construction","faufale","n."],
["Consul","konesula","n."],
["consult","felogoa'i","v."],
["consult","taupule","v."],
["contagious","pipisi","adj."],
["continent","konitineta","n."],
["continually","saga","adv."],
["continue","fa'aauau","v."],
["continue","fa'asolosoloina","v."],
["continue","utuva","v."],
["contribution","togima'a","n."],
["contribution","sao","n."],
["control","pulea","v."],
["cooked","vela","adj."],
["cooking","kuka","n."],
["cool (weather)","malu","adj."],
["cool off, shower","fa'amalu","n."],
["cooler","pusa'aisa","n."],
["copy","kopi","n."],
["coral","'amu","n."],
["cork","momono","n."],
["corn","saga","n."],
["corned beef","pisupo","n."],
["corner","tulimanu","n."],
["correct","fa'asa'o","v."],
["correct","fa'atonu","v."],
["correct","sa'o","adj."],
["correct","agatonu","v."],
["correspond","fetaui","v."],
["correspond","fetusia'i","v."],
["cost","tau","n."],
["cotton (like)","vavae","n."],
["cough","tale","v."],
["cough","kale ","v."],
["cough medicine","vaitale","n."],
["counsel","faulalo","v."],
["counsil","fa'alapotopotoga","n."],
["count","faitau","v."],
["country","atunu'u","n."],
["countrymen","tagatanu'u","n."],
["couragous","lototele","adj."],
["court hearing","fa'amasinoga","n."],
["cousin","tei","n."],
["cover","fa'amalu","v."],
["cover","pupuni","v."],
["cover (cooking)","tao","v."],
["cover for food","afugia","n."],
["cover up","fa'aufifui","v."],
["cover with sheet","'afu","v."],
["cow","povi","n."],
["coward","pala'ai","n."],
["cowboy","kaupoe","n."],
["crabs","pa'a","n."],
["crack","gapa","n."],
["cracked","isi","adj."],
["cracker","masi","n. "],
["crawl","tolotolo","v."],
["crazy","soso","adj."],
["cream","kulimi","n."],
["create","foafoa","v."],
["creation","foafoaga","n."],
["cricket","kilikiti","n."],
["cricket (insect)","'alisi","n."],
["criminal","pagota","n."],
["crippled","pipili","adj."],
["criticism","faitioga","n."],
["criticize","faitio","v."],
["criticize","tilotilomasae","v."],
["criticize","muimui","v."],
["crook","kuluku","n."],
["crooked","pi'o","adj."],
["crooked leg","vaepi'o","n."],
["crop","to'aga","n."],
["cross","sataulo","n."],
["cross","sopo'ia","v."],
["crow","vivini","v."],
["crow","koko'e","v."],
["crowded","tumu","adj."],
["crown for head","pale","n."],
["crucifix","fa'asataulo","n."],
["cruel","saua","adj."],
["crunchy","manutinuti","adj."],
["crush","'o'omi",""],
["crush to dust","nutipala","v."],
["cry","tagi","v."],
["cry","tutulu","v."],
["cubic","kupita","adj."],
["cucumber","kukama","n."],
["cultivate","fa'ato'a","v."],
["cultivate","galuea'ina","v."],
["culture","aganu'u","n."],
["culture or nature","fa'afailele","v."],
["culvert","alavai","n."],
["cup","ipu","n."],
["cupboard","kapoti","n."],
["current","tafega","n."],
["curry","kale","n."],
["curse","fetu'u","v."],
["curse someone","fa'amalaia","v."],
["curtain","'ie pupuni","n."],
["cut","'oti","v."],
["cut","tatipi","v."],
["cut","tipi","v."],
["cut","sogi","v."],
["cut (by knife)","lavea","v."],
["cut (grass)","sasa","v."],
["cut grass","sasavao","v."],
["cut up (animal)","pena","v."],
["cut off","mutu","v."],
["cut up (a fish)","fa'aio","v."],
["cyclone","afa","n."],
["dad","papa","n."],
["damage","fa'aleaga","v."],
["damage","fa'asaunoa","v."],
["dance","sa'asa'a","v."],
["dance","sausaunoa","v."],
["dance","siva","v."],
["dance (support)","'aiuli","v."],
["dangerous","mata'utia","adj."],
["dark","pogisa","adj."],
["dark (colors)","malosi","adj."],
["darling, dear","pele ","n."],
["daughter of chief","taupou","n."],
["daughter of man","afafine","n."],
["dawn","vaveao","n."],
["day","aso","n."],
["day after tom.","talatu taeao","n."],
["day before yest.","talatu ananafi","n."],
["daytime","ao","n."],
["deadline","gata ai","n."],
["deaf","logonoa","adj."],
["deaf","tutuli","adj."],
["deaf","tutuli","adj."],
["death","oti","n."],
["death","pe","n."],
["debt","'aitalafu","n."],
["deceive","fa'aoleole","v."],
["December","Tesema","n."],
["decieve","'olegia","v."],
["decieve","'o'ole","v."],
["decision","i'uga","n."],
["decision","fa'atofala'iga","n."],
["decision","tonu","n."],
["deck of ship","fogava'a","n."],
["decorate","fa'amatagofie","v."],
["decorate","tapena","v."],
["decorate","teu","v."],
["decorate","teuteu","v."],
["decoration","teuga","n."],
["decrease","fa'aititi","v."],
["deep","loloto","adj."],
["deep sea","moana","n."],
["defeat","to'ilalo","v."],
["defeated","malolo","v."],
["defeated","to'ilalo","adj."],
["defecate","ti'o","v."],
["define","fa'amanino","v."],
["definition","fa'auigaga","n."],
["degree","tikeri","n."],
["delay or prolong","fa'atuai","v."],
["delicacy","seasea","n."],
["delicious","manaia","adj."],
["deliver","tiliva","v."],
["deliver something ","fa'ao'o","v."],
["denomination","tapua'iga","n."],
["dent","omo","n."],
["deny","fa'afiti","v."],
["depart","fa'ae'e","v."],
["depart or leave","te'a","v."],
["department","matagaluega","n."],
["depend","fa'alagolago","v."],
["depends","fuafua","v."],
["desert","toafa","n."],
["desire","fia","v."],
["desire","finagalo","v."],
["desire","mo'omo'o","v."],
["desire","mo'omo'oga","n."],
["desire earnestly","naunau","v."],
["desired","mo'omia","adj."],
["desk","kesi","n."],
["despise","manatu fa'atauva'a","v."],
["destination","taunu'uga","n."],
["destroy","fa'a'umatia","v."],
["destructive","fa'atautala","adj."],
["determined","mafuli","v."],
["devastated","fa'atama'ia","adj."],
["devil","tevelo","n."],
["devil","ti'apolo","n."],
["dial","vili","v."],
["diameter","taiamita","n."],
["diamond","taimane","n."],
["die","maliu","v."],
["die (non-human)","mate","v."],
["difference","'ese'esega","n."],
["different","'ese","adj."],
["different","'ese'ese","v."],
["difficult","faigata","adj."],
["difficult","fita","adj."],
["difficult to say","ta'ugata","ad."],
["difficulty","mea faigata","n."],
["dig","'eli","v."],
["dig","sua","v."],
["dig up","vane","v."],
["dignity","mamalu","n."],
["diligent","to'aga","adj."],
["dilute (with water)","sui","v."],
["diploma","tipiloma","n."],
["direct","fa'atautaia","v."],
["direction away","'ese","adv."],
["director","fa'atonusili","n."],
["dirt","palapala","n."],
["dirty","'ele'elea","adj."],
["dirty","palapala","adj."],
["disadvantage","ituleaga","n."],
["disagree","fa'ataute'e","v."],
["disagree","felotoa'i","v."],
["disappear","leiloa",""],
["disappear","nimo","v."],
["disappear","nimo","v."],
["disappea","galoma","v."],
["disappointed","lotomafatia","adj."],
["discourage","fa'alotovaivai","v."],
["discuss","fa'amatala","v."],
["discuss","fa'atalanoa","v."],
["disease","fa'ama'i","n."],
["disembowel","fa'atiau","v."],
["dismiss","ta'ape","v."],
["dismissal","te'aga","n."],
["disobedient","'augata","adj."],
["disobedient","fa'alogogata","adj."],
["disobey","fa'ataute'e","v."],
["disown a child","fa'ato","v."],
["display","fa'aaliga","n."],
["disrespectul","fa'aaivao","adj."],
["disrespectul","fa'alemigao","adj."],
["dissapointed","a'oa'i","v."],
["distress","mafatiaga","n."],
["distress","puapuaga","n."],
["distressed","atuatuvale","adj."],
["distressed (love)","mutimutivale","v."],
["distribute","tufa","v."],
["distribute","vaevae","v."],
["distribute","fa'asoa","v."],
["district","itumalo","n."],
["disturb","fa'alavelave","v."],
["disturbed","vevesi","v."],
["ditch","'autu","n."],
["dive","tofu","v."],
["dive into water","maulu","v."],
["divide","tofi","v."],
["divide","tofitofi","v."],
["divide","vaevae","v."],
["divide","vavae","v."],
["divide in four","vaefa","v."],
["divide in to parts","vavae","v."],
["divide in two","vaelua","v."],
["divorce","tete'a","v."],
["divorce","tusi alei","n."],
["dizzy","niniva","adj."],
["do","fai","v."],
["do laundry","tamea","v."],
["do please","se'i","com."],
["do quickly","fa'atopetope","v."],
["do regurarly","faiso'o","v."],
["do halfway","fa'aafa","v."],
["Do you think?","fa'amata","q."],
["doctor","foma'i","n."],
["doesn't matter","e le afaina","phrs."],
["dog","maile","n."],
["dog","ta'ifau","n."],
["doing","faiga","n."],
["dollar","tala","n."],
["donate","foa'i","v."],
["donation","taulaga","n."],
["donation","pereti","n."],
["done","'uma","adj."],
["done carelessly","so'ona fai","adj."],
["don't","'aua","com."],
["door or gate","faitoto'a","n."],
["doubt","masalosalo","v."],
["dove","lupe","n."],
["down","ifo","dir."],
["down","lalo","adv."],
["dozen","taseni","n."],
["draw","tusi","v."],
["draw near","fa'alatalata","v."],
["drawer","tapoti","n."],
["dream","miti","v."],
["dregs","'alu","n."],
["dress ","fa'aofu","v."],
["dried up ","magumagu","adj."],
["drift","tafea","v."],
["drift","tafetafea","v."],
["drifter lifestyle","maumausolo","n."],
["drill","vili","v."],
["drink","inu","v."],
["drink","meainu","n."],
["drink","taumafa","v."],
["drink","taute","v."],
["drip","sisina","v."],
["drive","'ave","v."],
["drive","fa'auli","v."],
["drive or steer","fa'auli","v."],
["driver","'aveta'avale","n."],
["driver's license","laisene 'aveta'avale","n."],
["drop","pa'u","v."],
["drop into eyes ","tului","v."],
["drown","malemo","v."],
["drown someone","lelemo","v."],
["drowsy","matamoe","adj."],
["drowsy","tulemoe","adj."],
["drummer","kakigipalau","n."],
["drunk","'ona","adj."],
["dry","mago","adj."],
["duck","pato","n."],
["dumb","gugu","adj."],
["durable","'anagata","adj."],
["dust","efuefu","n."],
["dust","pefu","n."],
["duty","tiute","n."],
["duty","tofi","n."],
["dynamite","fanai'a","n."],
["each","ta'i","adj."],
["ear","taliga","n."],
["earlier today","analeila","n."],
["earlier in morning","anataeao","n."],
["early","vave","v."],
["earth","lagolagi","n."],
["earthquake","mafui'e","n."],
["earwax","taetuli","n."],
["east","sasa'e","n."],
["Easter","'Eseta","n."],
["easy","faigofie","adj."],
["eat","'ai","v."],
["eat","tali le sua","v."],
["eat","taumafa","v."],
["eat","tausami","v."],
["eat","taute","v."],
["eat standing","'aitu","v."],
["eclipse","gasetoto","n."],
["edge","pito","n."],
["education","a'oa'oga","n."],
["eel","tuna","n."],
["eerie","pau","adj."],
["egg","fuamoa","n."],
["eggplant","'isara'elu","n."],
["eight","valu","num."],
["eighth","lona valu","adj."],
["elbow","tulilima","n."],
["election","palota","n."],
["electric","'eletise","n."],
["electricity","uila","n."],
["elephant","'elefane","n."],
["elephantitis","mumu","n."],
["elevate","ea","v."],
["embarass","fa'amaasiasi","v."],
["embarrassed","ma","adj."],
["embrace","fusimau","v."],
["embrace in arm","opoopo","v."],
["empty","atigi","adj."],
["empty bottle","atigifagu","n."],
["encounter","fetaiai","v."],
["encourage","tima'i","v."],
["encourage","fetima'i","v."],
["encouragement","tima'iga","n."],
["end","i'uga","n."],
["end","fa'ai'u","v."],
["end (road)","tulu'iga","n."],
["end (work)","manava","n."],
["end of day","afiafi po","adj."],
["end or result in","i'u","adj."],
["end, terminate","gata","v."],
["endear","fa'apelepele","v."],
["endure long time","fa'afualoa","v."],
["endure","fa'apalepale","v."],
["enemy","fili","n."],
["engagement","tusiga","n."],
["engineer","'inisinia","n."],
["engineering","fa'ainisinia","n."],
["England","'Egelani","n."],
["engrave","togitogi","v."],
["enhancement","fa'amamaluga","v."],
["enjoy","fiafia","v."],
["enough","lava","adj."],
["enrich","fa'atamao'aigaina","v."],
["enrol","fa'aulu","v."],
["enslave","fa'apologa","v."],
["enter","ulu","v."],
["enter (a building)","ulufale","v."],
["entertain","fa'afiafia","v."],
["entertainment","fa'afiafiaga","n."],
["entire","'atoatoa","adj."],
["entirely","'atoatoa","adv."],
["entrance (house)","ulufale","n."],
["envelope","teutusi","n."],
["envious","lotovale","adj."],
["environment","si'osi'omaga","n."],
["equal","tutusa","n."],
["equally","gatasi","n."],
["erase (duster)","solo","v."],
["eraser","titina","n."],
["erect","fa'atu","v."],
["errand","fe'au","n."],
["escape","sola","v."],
["escort","momoli","n."],
["especially","'aimaise","adv."],
["essay","tusigatala","n."],
["establish ties","fa'aaiga","v."],
["establish firmly","fa'atumau","v."],
["estimate","oka","n."],
["estimate","tao fa'ata'ita'i","n."],
["eternal","fa'avavau","adv."],
["European house","falepalagi","n."],
["even","laulelei","adj."],
["evening meal","taligasua","n."],
["every","uma","adj."],
["exaggerate","'ova","v."],
["exam","su'ega","n."],
["examination","iloiloga","n."],
["example","fa'ata'ita'iga","n."],
["exceedingly","naua","adj."],
["exceedingly","naunau","adj."],
["excellent","ma'eu","adj."],
["except","vagana","conj."],
["excercise","fa'amalositino","v."],
["exchange","fesuia'i","v."],
["exchange","fesuia'i","v."],
["exchange speech","fetalia'i","v."],
["excite or stir up","fa'aoso","v."],
["excuse me","tulou","interj."],
["exhausted","le lava","adj."],
["exhibition","fa'aailga","n."],
["exist","iai","v."],
["exit ( a building)","ulufafo","n.v."],
["expand","fefete","v."],
["expand on a topic","fa'alautele","v."],
["expect","fa'amoemoe","n."],
["expel","fa'ate'a","v."],
["expel","tuli","v."],
["expenses","fa'aalu tupe","n."],
["expensive","taugata","adj."],
["experience","'agava'a","n."],
["expert","tufuga","n."],
["explain","fa'amatala","v."],
["explain","fa'amalamalama","v."],
["explanation","fa'amalamalamaga","n."],
["explanation","fa'amatalaga","n."],
["explode","pa","v."],
["exports","'oloa ave fafo","n."],
["expose to  sun","fa'ala","v."],
["exposed to sun","laina","v."],
["express","momoli","v."],
["express opinion","finau","v."],
["expression","fa'a'upuga","n."],
["extinguish (fire)","tape","v."],
["extinguish (fire)","tinei","v."],
["eyeglasses","matatioata","n."],
["eyeglasses","tioata","n."],
["eyelid","laumata","n."],
["eyes","mata","n."],
["face","fetaiai","v."],
["face","fofoga","n."],
["face","foliga","n."],
["face (in direction)","fa'asaga","v."],
["face of the earth","fogaeleele","n."],
["face upwards","fa'ataliaga","v."],
["factory","falegaosimea","n."],
["faint","matapogia","v."],
["fair","fea","adj."],
["fairy tale","fagogo","n."],
["faithful","maoni","adj."],
["fall","palasi","v."],
["fall","pa'u","v."],
["fall (facefirst)","sulu","v."],
["familiarize","fa'amasani","v."],
["family","'aiga","n."],
["famine","oge","n."],
["famous","lauiloa","adj."],
["famous","ta'uta'ua","adj."],
["fan","ili","n."],
["fan","fuefue","v."],
["fan (someone)","tapili","v."],
["far","mamao","adj."],
["fare","pasese","n."],
["farewell","fa'amavae","v."],
["farewell","fa'amavaega","n."],
["farm","fa'ato'aga","n."],
["farmer","faifa'atoaga","n."],
["farther inland","uta","n."],
["fast","saoasaoa","adj."],
["fast","vave","adj."],
["fast (no food)","anapogi","n."],
["fasten","fa'amau","v."],
["fat","lapo'a","adj."],
["fat (of people)","puta","adj."],
["fat or grease","ga'o","n."],
["father","tama","n."],
["Father's Day","Aso Sa o Tama","n."],
["fatty","lololo","adj."],
["fault (in wood)","pona","n."],
["favor","mealelei","n."],
["favorite (food)","ma'oi","n."],
["fear","fefe","n."],
["fear","mata'u","n."],
["feast","taumafataga","n."],
["feather","fulu","v."],
["February","Fepuari","n."],
["feces","tae","n."],
["fed up","fiu","v."],
["feed","fafaga","v."],
["feel","lagona","v."],
["feel","tago","v."],
["feeling","loto","n."],
["feeling trouble","fa'ali'ali'a","adj."],
["feeling of person","agaga","n."],
["fellowship","mafutaga","n."],
["fence","pa","n."],
["fertilize","fa'alelei ele'ele","v."],
["fertilizer","fetilaisa","n."],
["fetch","a'ami","v."],
["fever","fiva","n."],
["few","to'aitiiti","adj."],
["few","to'alaititi","adj."],
["few (plural of si)","nai","art."],
["few in number","gaogao","adj."],
["field","malae","n."],
["fierce or vicious","fe'ai","adj."],
["fifth","lona lima","adj."],
["fight","fusu","v."],
["fight","misa ","n."],
["figure","fika","n."],
["filarisis","fiva mumu","n."],
["file","faila","n."],
["fill","utu","v."],
["fill","fa'atumu","v."],
["fill out","fa'atumu","v."],
["filter","fa'amama","v."],
["fin","gogo","n."],
["final","tupito","adj."],
["finally","fa'ai'u ona","adv."],
["find","su'e","v."],
["fine","manaia","adj."],
["fine","sala","n."],
["fine mat","'ie toga","n."],
["finger","tama'ilima","n."],
["fingernails","atigilima","n."],
["finish","'uma","v."],
["finish","tu'ua","v."],
["finsished","mae'a","v."],
["fire","afi","n."],
["fire (gun)","fa'apa","v."],
["fire (someone)","fa'amalolo","v."],
["firewood","fafie","n."],
["firm","uamau","adj."],
["firm","malo","adj."],
["firm","mau","adj."],
["firm","mautu","adj."],
["first","ulua'i","adj."],
["first","muamua","n."],
["first priority","fa'amuamua","n."],
["fish","i'a","n."],
["fish","fagota","v."],
["fish (type of)","ume","n."],
["fish hook","matau","n."],
["fish market","falei'a","n."],
["fish soup","suai'a","n."],
["fisherman","faifaiva","n."],
["fishing (art of)","faiva","v."],
["fishing net","upega","n."],
["fish with net","tili","v."],
["fishing spear","matatao","n."],
["fist","moto","n."],
["fit (enough space)","ofi","v."],
["fit for a king","fa'atupu","adj."],
["five","lima","num."],
["flag or banner","fu'a","n."],
["flare","felea","v."],
["flat","mafolafola","adj."],
["flat","papa","adj."],
["fleet of ships","fua","n."],
["flexible","vavai","adj."],
["float","opeopea","v."],
["float","upeupea","v."],
["flood","lolo","v."],
["floor","fola","n."],
["floor","foloa","n."],
["flour","falaoamata","n."],
["flourish","uluola","v."],
["flow","tafe","v."],
["flow swiftly","tatafe","v."],
["flower","fuga","n."],
["flower","fugala'au","n."],
["flu","fulu","n."],
["fly","lele","v."],
["fly (bug)","lago","n."],
["flying fox","pe'a","n."],
["focus","taula'i","v."],
["fold, crease","gaugau","v."],
["follow","fa'aafu","v."],
["follow","mulimuli","v."],
["follow","tulitatao","v."],
["food","'ava","n."],
["food","mea'ai","n."],
["food (as a gift)","oso","n."],
["food offered","aso","n."],
["food in throat ","laoa","n."],
["fool","fa'avalea","v."],
["fool","vale","n."],
["foolish","valea","adj."],
["foolish or idiotic","fa'avalevalea","adj."],
["foot","vae","n."],
["foot (measure)","futu","n."],
["footprint","tulagavae","n."],
["for","ma","prep."],
["for","mo","prep."],
["forbid or prohibit","fa'asa","v."],
["forbidden","tapu","v."],
["forbidden","sa","v."],
["force","fa'amalosi","v."],
["forehead","muaulu","n."],
["foreman","'ovasia","n."],
["forest (deep)","vaomatua","n."],
["forever","fa'avavau","adv."],
["forget","galo","v."],
["forget completely","galo nimo","v."],
["forget (intent)","fa'agalogalo","v."],
["forgive","fa'amagalo","v."],
["forgiven","magalo","v."],
["forgive (event)","ifoga","n."],
["forgiving","loto fa'amagalo","adj."],
["fork","tui","n."],
["form a circle","fa'ata'ali'oli'o","v."],
["fortunate","manuia","adj."],
["found","maua","v."],
["foundation","fa'avae","n."],
["four","fa","num."],
["four corners","magafa","n."],
["fourth","lona fa","adj."],
["France","Falani","n."],
["free","fua","adj."],
["free","sa'oloto","adj."],
["free (set free)","fa'asa'oloto","v."],
["free (no restrict.)","gafua","v."],
["freedom","sa'olotoga","n."],
["freezer","pusa'aisa","n."],
["fresh (water)","magalo","adj."],
["fresh water","suavai","n."],
["Friday","aso faraile","n."],
["friend","uo","n."],
["friendship","faigauo","n."],
["frog","lane","n."],
["from","mai","prep."],
["from (from inside)","nai","prep."],
["front","luma","dir."],
["front row","atualuma","n."],
["frown","fa'asiasia","v."],
["frown","matafa'a'u'u","v."],
["fruitbearing","ma'ave'ave","adj. "],
["fry","falai","v."],
["full","tumu","adj."],
["full (food)","laulelei","adj."],
["full (food)","ma'ona","adj."],
["full (moon)","'atoa","adj."],
["full (of people)","fa'atumulia","adj."],
["fumble","pa'ela","v."],
["fund","fa'aputugatupe","n."],
["funeral home","falelauasiga","n."],
["funnel","fa'atumu","n."],
["funny","malie","adj."],
["funny man","fa'aluma","n."],
["funny taste","malamala","n."],
["funural","maliu","n."],
["furniture","meafale","n."],
["further inland","maouta","adj."],
["further out to sea","maotai","adj."],
["further to back","maotua","adj."],
["future","lumana'i","n."],
["gallon","kalone","n."],
["game","ta'aloga","n."],
["garage","faleta'avale","n."],
["gardener","faitogala'au","n."],
["gas","kesi","n."],
["gasoline","penisini","n."],
["gasp (for breath)","sela","v."],
["gather","aofia","v."],
["gather","fa'aputuputu","n."],
["gather from tree","toli","n."],
["gather nuts","tufi","v."],
["gather together","potopoto","v."],
["gathering","fa'apotopotoga",""],
["gauze","kosi","n."],
["gear","kia","n."],
["geneology","gafa","n."],
["generation","tupulaga","n."],
["generous","limafoa'i","adj."],
["generous","matamau","adj."],
["genitals","mea","n. "],
["Germany","Siamani","n."],
["germs","siama","n."],
["get","maua","v."],
["get rid of","tia'i","v."],
["ghost","aitu","n."],
["giant clam","faisua","n."],
["gift","meaalofa","n."],
["ginger","fiu","n."],
["girl","teine","n."],
["girl","suga","n."],
["give","fa'afao","v."],
["give","foa'i","v."],
["give ","'avatu ","v."],
["give (to direction)","'avane","v."],
["give a fair share","fa'asalafa","v."],
["give me","'aumai","v."],
["give back","fa'afo'i","v."],
["glance","tepa","v."],
["glance","tilotilo","v."],
["glass","ipu malamalama","n."],
["glass","tioata","n."],
["globe","kelope","n."],
["glory","vi'iga","n."],
["glue","kelu","n."],
["gnaw","'ati","v."],
["gnaw","gali","v."],
["go","aga'i","v."],
["go","alu","v."],
["go","o","v."],
["go (polite)","afio atu","v."],
["go abroad","fa'ae'e","v."],
["go along","ui","v."],
["go around","ta'amilo","v."],
["go away","alu 'ese","v."],
["go backwards","solomuli","v."],
["go fishing","tautai","v."],
["go for walk","savalivali","v."],
["go in a circle","fa'ata'amilo","v."],
["go out","tafao","v."],
["go repeatedly","utu alu","v."],
["go straight","alu sa'o","v."],
["go to school","ao'oga","v."],
["goal","'ai","n."],
["goal","tini","n."],
["goal","sini","n."],
["goal","fa'amoemoega","n."],
["god","atua","n."],
["gold","aulo","n."],
["gold","auro","n."],
["gold","lanu 'auro","adj."],
["good","lelei","adj."],
["good","manuia","n."],
["good behavior","agalelei","adj."],
["good conduct","amiolelei","adj."],
["Good Friday","Aso Maliu","n."],
["good health","soifuaga","n."],
["good looking","'aulelei","adj."],
["good looks","matagofie","adj."],
["goodbye","tofa","n."],
["goodbye","tofa soifua","interj."],
["goods","'oloa","n."],
["goose","kusi","n."],
["gospel","tala lelei","n."],
["govern","fa'atautaia","v."],
["govern","pulea","v."],
["governer","kovana","n."],
["government","malo","n."],
["grab","se'i","v."],
["grace","lotu","n."],
["graduate","fa'au'u","v."],
["graduation","fa'au'uga","n."],
["grammar","kalama","n."],
["grapes","vine","n."],
["grasp","tago","v."],
["grass","mutia","n."],
["grass","vao","n."],
["grated coconut","panu","n."],
["grateful","lotofa'afetai","adj."],
["grave changing","liutofaga","n."],
["gravel","'ili'ili","n."],
["gravel","paepae","n."],
["gravy","kaleve","n."],
["graze or abrazion","maosia","n."],
["greasy","ga'oa","adj."],
["greed","matape'ape'a","adj."],
["greedy","fa'aloloto","adj."],
["green","lanu meamata","adj."],
["green pepper","polo meamata","n."],
["greet","fa'atalofa","v."],
["grey","'efu'efu","adj."],
["grey","lanu 'efu'efu","adj."],
["grey (hair)","sina","adj."],
["grind","fa'amanifi","v."],
["groomsman","uomamai","n."],
["grope","tauto'ai","v."],
["grope (in dark)","autago","v."],
["group","vaega","n."],
["group of orators","faleupolu","n."],
["group, team","'au","n."],
["grow","atili","v."],
["grow","tupu","v."],
["grub","'afato","n."],
["grunt","'ua","v."],
["grunt","'ua'ua","v."],
["guard","leoleo","n."],
["guava","kuava","n."],
["guess","mate","n."],
["guess","taumate","n."],
["guest","malo","n."],
["guest house","faletalimalo","n."],
["guide","ta'ita'i","v."],
["guidelines","ta'iala","n."],
["guitar","kitala","n."],
["gum (chewing)","pulu","n."],
["gun","fana","n."],
["gunpowder","oge","n."],
["hair","laulu","n."],
["hair","lauulu","n."],
["haircut","'oti le ulu","n."],
["haircut","fa'afuga","n."],
["half","'afa","adj."],
["halfcaste","'afatasi","n."],
["hammer","tutu'i","v."],
["hammer","samala","n."],
["hand","lima","n."],
["hand down","tu'ufa'asolo","v."],
["handsome","'aulelei","adj."],
["handspan (mats)","aga","n."],
["hang (clothes)","tautau","v."],
["hang firmly","taumau","v."],
["hang out","eva","v."],
["hang out","tafao","v."],
["hang","tautau","v."],
["hankerchief","solosolo","adj."],
["happen","o'o","v."],
["happen","tupu","v."],
["happy","fiafia","adj."],
["harbour","taulaga","n."],
["hard","faigata","adj."],
["hard","malo","adj."],
["hard to break","ma'a'a","adj."],
["hardship","mea faigata","n."],
["harvest","fua mai","v."],
["harvest","se'i","v."],
["harvest","selesele","v."],
["harvest taro","se'i fafai","v."],
["hasty","topelau","adj."],
["hat","pulou","n."],
["hate","'ino'ino","v."],
["hated or disliked","'inosia","adj."],
["have","iai","v."],
["have","maua","v."],
["have (meeting)","fai","v."],
["have a hole","pu","adj."],
["have confidence in","talisapaia","v."],
["hazy or unclear (a subject)","fa'anenefu","adj."],
["he","ia","dem."],
["he","na","v."],
["head","ulu","n."],
["headline","talatomua","n."],
["headstrong","fa'ali'i","adj."],
["headware for a taupou dancer","tuiga","n."],
["heal","fa'amalolo","v."],
["healing","fa'amaloloina","v."],
["healthy","maloloina","adj."],
["heap or mound","fauupu'ega","n."],
["heaped up or abound","faula'i","v."],
["hear","fa'afofoga","v."],
["hear","fa'alogo","v."],
["heart","fatu","n."],
["heartbroken","lotomomomo","adj."],
["heartless","lotomomotu","adj."],
["heat","fa'avevela","v."],
["heat up a fire","fa'aa'asa","v."],
["heaven","lagi","n."],
["heavy","mamafa","adj."],
["heel","mulivae","n."],
["heir","suli","n."],
["hello","talofa","interj."],
["help","fesoasoani","v."],
["her","ana","possprn."],
["her","ona","possprn."],
["her","lana","possprn."],
["her","lona","possprn."],
["her","sana","possprn."],
["her","sona","possprn."],
["herd","lafu","n."],
["herd","ta'aga","n."],
["here","'i","dir."],
["here","'i 'i","dir."],
["here","'i 'inei","dir."],
["here","'inei","n."],
["here","leia","dem."],
["hermit crab","ula","n."],
["hi","malo","interj."],
["hiccup","to'omaunu","n."],
["hicup","loga","n."],
["hide","lafi","v."],
["hide something","nana","v."],
["hiding place","lafiga","n."],
["high","maualuga","adj."],
["high (water level)","sua","adj."],
["high chief","ali'imatua","n."],
["high chief","ali'itaua","n."],
["High chief house","maota","n."],
["High Commission","Hikomisi","n."],
["HighCommissioner","Haikomesina","n."],
["high tide","sua le tai","adj."],
["hill","a'ega","n."],
["his","ana","possprn."],
["his","ona","possprn."],
["his","lana","possprn."],
["his","lona","possprn."],
["his","sana","possprn. "],
["his","sona","possprn."],
["history","tala'aga","n."],
["hit","ta","v."],
["hit (by car)","lavea","v."],
["hit (person)","fasi","v."],
["hold","u'u ","v."],
["hold","mau","v."],
["hold (in hands)","opo","v."],
["hole","'omo","n."],
["holiday","Aso malolo","n."],
["holidays","tu'uaga","n."],
["hollow","'o'o","adj."],
["holy","pa'ia","adj."],
["holy spirit","agaga paia","n."],
["homesick","ma'i manatu","adj."],
["homework","meaa'oga","n."],
["honest","fa'amaoni","adj."],
["honey","meli","n."],
["honor","fa'amamalu","v."],
["hoot","talie","v."],
["hope","fa'amoemoe","v."],
["hope","talotalo","v."],
["hope (pray)","talosia","v."],
["horrible","mata'utia","adj."],
["hospital","falema'i","n."],
["hospitality","fa'aaloalo","n."],
["host","talimalo","v."],
["hot","feu","adj."],
["hot","vevela","adj."],
["hot (the sun)","a'asa","adj."],
["hot bottle","fagupa'u","n."],
["hotel","faletalimalo","n."],
["hour","itula","n,"],
["household items","'anofale","n."],
["hover","tifa","v."],
["How","'E a","q."],
["How","'E fa'apefea","q."],
["How","'O a","q."],
["how","fa'afefea","q."],
["How are","'O a mai","q."],
["How many","'E fia","q."],
["how many","fia","q."],
["How many each","ta'ifia","q."],
["How many people","'E to'afia","q."],
["how many times","fa'afia","q."],
["how many?","to'afia","q."],
["How much","'E fia le","q."],
["how?","fa'apefea","q."],
["however","e ui lea","conj."],
["hug","fusi","v."],
["humble","fa'atauva'a","adj."],
["humble","lotomaualalo","adj."],
["humble","lotomaualalo","adj."],
["hundred","selau","n."],
["hungry","fia'ai","adj."],
["hunt","tulimanu","v."],
["hunt","tutuli","v."],
["hurricane","afa","n."],
["hurried","topevale","adj."],
["hurry","fa'anatinati","v."],
["hurry","fa'avave","v."],
["hurry","matele","v."],
["hurry","tope","v."],
["hurry","tili","v."],
["hurry up","faia'ia","com."],
["hurt","tiga","v."],
["husband","tane","n."],
["hush","fa'ana","v."],
["husk","o'a","v."],
["husk (coconuts)","mele'i","v."],
["hyena","haena","n."],
["hygiene","tumama","n."],
["I","a'u","prn."],
["I","'Ou","prn."],
["ice","'aisa","n."],
["ice cream","'asikulimi","n."],
["ice water","vaiaisa","n."],
["ice-cream","'aisikulimi","n."],
["idea","aikia","n."],
["idea","auala","n."],
["identify","fa'ailoa","v."],
["identity card","pepa fa'amaonia","n."],
["idol","tupua","n."],
["idols","atua le gagana","n."],
["if","a","conj."],
["if","pe'afai","conj."],
["if","pe'ana","conj."],
["if (past)","'ana","conj."],
["ignore","fa'agalo","v."],
["ignore","fa'atuatuana'i","v."],
["imitate","fa'ata'ita'i","v."],
["imitate","fa'aa'oa'o","v."],
["immediate family ","lotoifale","n."],
["immediately","loa","adv."],
["immerse","fa'atofu","v."],
["import","aumai fafo","v."],
["important","taua","adj."],
["improvement","aga'i i luma","n."],
["in","i","prep."],
["in","totonu","prep."],
["in (before name)","ia","v."],
["in accordance","talafeagai","v."],
["in order to, so that","'ina 'ia","conj."],
["in teams","fai'au","v."],
["in the thick of","lotolotoi","v."],
["inadequate","'uti'uti","adj."],
["incest","mata'ifale","v."],
["inch","'inisi","n."],
["include","a'afia","v."],
["increase","atili","v."],
["increase","fa'ateleina","v."],
["increase","tului","v."],
["indebted","nofo aitalafu","v."],
["indented","'omo","adj."],
["independence","tuto'atasi","n."],
["infected","'ona","adj."],
["information","fa'amatalaga","n."],
["inheritance","tu'ufa'asolo","n."],
["inject","tui","v."],
["ink","vaitusi","n."],
["inland","uta","n."],
["inside","totonu","adv."],
["inside of  coconut","o'o","n."],
["insignificant ","fa'atauva'a","adj."],
["inspection","asiasiga","n."],
["inspire courage","fa'alototele","v."],
["institution","fa'alapotopotoga","n."],
["instruct","fa'atonu","v."],
["insufficient","'uti'uti","adj."],
["insult","faifai","v."],
["interfere","fa'alavelave","v."],
["internal organs","totoga","n."],
["internet","initaneti","n."],
["interrupt","fa'alavelave","v."],
["interupt","fa'asalavei","v."],
["interupt (speach)","talaoso","v."],
["intestines","ga'au","n."],
["intimate","mafana","adj."],
["intimidate ","fa'amata'u","v."],
["introduce (ideas)","fa'aali","v."],
["investigate","su'esu'e","v."],
["investivation","iloiloga","n."],
["invitation","val'aulia","n."],
["invite","vala'au","v."],
["Ireland","'Aialani","n."],
["iron (for clothes)","'auli","n."],
["iron bar","tolopa","v."],
["irritate","fa'aono'ono","v."],
["Is there","'E iai","q."],
["island","motu","n."],
["Israel","'Isara'elu","n."],
["issue","mataupu","n."],
["it","ia","dem."],
["it","na","prn."],
["It looks as if...","semanu","adv."],
["Italy","'Italia","n."],
["itch","mageso","v."],
["its","ana","possprn"],
["its","lana","possprn."],
["its","lona","possprn"],
["its","sana","possprn."],
["its","sona","possprn."],
["jack","siaki","n."],
["jail","falepuipui","n."],
["jam","siamu","n."],
["January","Ianuari","n."],
["Japan","Iapani","n."],
["Japan","Sapani","n."],
["jealous","fua","adj."],
["jealous","lotoleaga","adj."],
["jealous","matau'a","adj."],
["jeep","sipi","n."],
["jellyfish","'alu'alu","n."],
["Jesus","Iesu","n."],
["jog","toleni","v."],
["join","auai","v."],
["join","soso'o","v."],
["joke","talasua","n."],
["joke","tausua","v."],
["joke","tausuaga","n."],
["joyful","'oli'oli","v."],
["judge","fa'amasino","n."],
["juice or liquid","sua","n."],
["July","Iulai","n."],
["jump","oso","v."],
["jump about","feosofa'i","adj."],
["June","Iuni","n."],
["just now","ananei","n,"],
["just now, first time","fa'ato'a","adv."],
["just ok","feololo","adj."],
["kangaroo","kagalu","n."],
["karate","kalate","n."],
["kava","'ava","n."],
["keep","manoa","v."],
["keep","mau","v."],
["keep","teu","v."],
["keep","pea","v."],
["keep going","alu pea ","v."],
["keep in touch","fa'afeso'ota'i","v."],
["keg","paelo","n."],
["kerosene","kalasini","n."],
["key","ki","n."],
["kick","kiki","v."],
["kill (animal)","tape","v."],
["kill (person)","fasioti","v."],
["kilogram","kilokalama","n."],
["kind","itu'aiga","n."],
["kindness","agalelei","n."],
["king","tupu","n."],
["kiss","sogi","v."],
["kiss","kisi","v."],
["kiss (plural)","feasogi","v."],
["kitchen","umukuka","n."],
["kitchen","kuka","n."],
["kitchen(traditional)","fale paito","n."],
["knee","tulivae","n."],
["kneel","to'otuli","v."],
["knife","naifi","n."],
["knot or lashing","nonoa","n."],
["know","iloa","v."],
["know exactly what to do","osotatau","v."],
["lack something","'asa","v."],
["lacking water","naumati","adj."],
["ladder","apefa'i","n."],
["lady","tamai'ta'i","n."],
["lagoon","aloalo","n."],
["lake","vaituloto","n."],
["lamp","ula o afi","n."],
["lamp","moli","n."],
["land","fanua","n."],
["land","tulau'ele'ele","n."],
["landform","laufanua","n."],
["language","gagana","n."],
["lantern","molimatagi","n."],
["large","lapo'a","adj."],
["large meeting","fonotaga","n."],
["last","mulimuli","n."],
["last night","anapo","n."],
["last week","vaiaso ua te'a","n."],
["last, final","'amuli","adj."],
["late","tuai","adj."],
["later","nanei","adv."],
["latrine","fale'ese","n."],
["latrine","faleletaua","n."],
["laugh","'ata","v."],
["laugh","soisoi","v."],
["laugh (of a group)","toe","n."],
["laundromat","faleta'ofu","n."],
["laundry","tagamea","n."],
["lava (volcanic)","lava","n."],
["lavalava","'ie lavalava","n."],
["lavalava(pockets)","ie faitaga","n."],
["lawyer","loia","n."],
["lay a trap","lama","v."],
["lay down","ta'oto","v."],
["lay eggs","tautufua","v."],
["lay down (thing)","fa'ata'oto","v."],
["lazy","paie","adj."],
["lead","ta'i","v."],
["lead","tauata'i","v."],
["leader","ta'ita'i","n."],
["leaf","lau","n."],
["leaf","lau la'au","n."],
["leaky (house)","tutulu","adj."],
["lean","pipi'i","v."],
["lean on","toto'o","v."],
["learn","a'oa'o","v."],
["lease","lisi","n."],
["leather","pa'u","n."],
["lecture","tautalaga","n."],
["left","agavale","adj."],
["leg","vae","n."]
];//end of EnglishToSamoanWords
